package utils

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

func GenerateID() string {
	b := make([]byte, 8)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b)
}

func GetEnvWithDefault(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

func GetProjectRoot() string {
	if wd, err := os.Getwd(); err == nil {
		return wd
	}
	return "."
}

func GetExecutableDir() string {
	exe, err := os.Executable()
	if err != nil {
		return "."
	}
	return filepath.Dir(exe)
}

func GetDataDir() string {
	exeDir := GetExecutableDir()
	dataDir := filepath.Join(exeDir, "data")

	if err := os.MkdirAll(dataDir, 0755); err != nil {
		return exeDir
	}

	return dataDir
}

func GetDatabasePath() string {
	dataDir := GetDataDir()

	exe, err := os.Executable()
	if err != nil {
		return filepath.Join(dataDir, "oc-message-explorer.db")
	}

	exeName := filepath.Base(exe)
	ext := filepath.Ext(exeName)
	dbName := exeName[:len(exeName)-len(ext)] + ".db"

	return filepath.Join(dataDir, dbName)
}

func FormatTimestamp(ms int64) string {
	t := time.Unix(0, ms*int64(time.Millisecond))
	return t.Format(time.RFC3339)
}

func IsAutoGenerated(title string) bool {
	if title == "" {
		return false
	}
	titleLower := strings.ToLower(title)
	autoGeneratedPatterns := []string{
		"auto-generated",
		"auto generated",
		"previous query",
		"previous prompt",
		"history",
		"continue",
		"resume",
		"up arrow",
		"↑",
		"↑ arrow",
		"continuation",
		"duplicate",
		"copy of",
		"from history",
		"similar to",
		"related to",
	}

	for _, pattern := range autoGeneratedPatterns {
		if strings.Contains(titleLower, pattern) {
			return true
		}
	}

	return false
}

func GetSummaryTitle(summary any) string {
	if summary == nil {
		return ""
	}

	switch v := summary.(type) {
	case bool:
		return ""
	case string:
		return v
	case map[string]any:
		if title, ok := v["title"].(string); ok {
			return title
		}
		return ""
	default:
		return ""
	}
}

func Placeholders(count int) string {
	if count == 0 {
		return ""
	}
	return strings.Repeat("?,", count)[:count*2-1]
}

func GetDefaultOpenCodePath() string {
	if runtime.GOOS == "windows" {
		return filepath.Join(os.Getenv("LOCALAPPDATA"), "OpenChat")
	}
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(homeDir, ".openchat")
}

func OpenBrowser(url string) {
	var cmd *exec.Cmd

	switch runtime.GOOS {
	case "windows":
		cmd = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	case "darwin":
		cmd = exec.Command("open", url)
	case "linux":
		cmd = exec.Command("xdg-open", url)
	default:
		return
	}

	cmd.Start()
}

func ParseTimestamp(timestamp string) (time.Time, error) {
	return time.Parse(time.RFC3339, timestamp)
}

func Now() string {
	return time.Now().Format(time.RFC3339)
}

func StringToBool(s string) bool {
	b, err := strconv.ParseBool(s)
	return err == nil && b
}

func BoolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}

func IntToBool(i int) bool {
	return i == 1
}
